fix(torch): processing duplications
celestiaorg/torch pull request #3
Opened 2023-11-08 11:18 UTC by tty47

hello team!

small one, it fixes to add duplicates to the queue, that happened because the watcher sends an event for every container in the pod, but we only need it once.

cheers! 🚀 

closes: https://github.com/celestiaorg/devops/issues/577

cc: @celestiaorg/devops

2023-11-09 08:29 UTC, smuu commented on pkg/k8s/statefulsets.go
> +	lastProcessedName := ""
I'm curious how this works. So why do we need to save the lastProcessedName?

2023-11-09 09:17 UTC, Bidon15 commented on pkg/k8s/statefulsets.go
>  				}
this is not a really readable code design. Can you please make a private function that checks all these states? 

In addition,  why not go with a map structure?

2023-11-09 09:18 UTC, Bidon15 requested changes

2023-11-09 09:18 UTC, Bidon15 commented on pkg/k8s/statefulsets.go
>  			if strings.HasPrefix(statefulSet.Name, "da") {
please make the "da" here as a const variable

2023-11-10 08:20 UTC, Bidon15 requested changes
Another one and we are good to go 🔥

2023-11-10 08:20 UTC, Bidon15 commented on pkg/k8s/statefulsets.go
> +				// Perform necessary actions, such as adding the node to the Redis queue
design wise, you can do the following: 

1. Check if not ok, fail fast with error and exit the for loop
2. If ok, then you have a second if outside of the boundaries of the first if else one(where you have the ok checker) 
3. If you want to check all the objects in the channel, you need to store the error messages one by one and then exit the for loop. So far, as I understood the code, you are not intending to do so

2023-11-13 10:26 UTC, mojtaba-esk commented on pkg/k8s/statefulsets.go
> +				// Perform necessary actions, such as adding the node to the Redis queue
I do not have enough context to review the logic. Just one comment: we can remove a lot of those comments as the code is descriptive enough.

2023-11-13 10:59 UTC, mojtaba-esk approved these changes
LGTM

2023-11-13 11:22 UTC, Bidon15 approved these changes
Now you see how more neat it looks! 
Wonderful job 💪

2023-11-13 11:28 UTC, merged