fix: consensus metric
celestiaorg/torch pull request #4
Opened 2023-11-08 16:51 UTC by tty47

hello team!

Some context about this PR, Torch generates a metric to show how long the chain is running, but sometimes if the service is not available for any reason (*for example, when autodevops creates a new env, torch starts before the nodes*), it generates an issue.

This PR manages this situation creating a task in the background and checking if the end service is available every 10".

Any feedback is welcome!

Cheers! 🚀 

cc: @celestiaorg/devops 
closes: https://github.com/celestiaorg/devops/issues/571

2023-11-09 08:31 UTC, smuu approved these changes
lgtm

2023-11-09 09:28 UTC, Bidon15 requested changes

2023-11-09 09:28 UTC, Bidon15 commented on pkg/http/server.go
> +
It's better to separate this into dedicated functions
In addition they need to return errors and we need to handle them properly

2023-11-09 09:28 UTC, Bidon15 commented on pkg/metrics/metrics.go
> +func CalculateDaysDifference(inputTimeString string) (int, error) {
You technically don't need this as a public func isn;t it?

2023-11-10 08:30 UTC, Bidon15 requested changes
Nice try! Another round to make it good 🥳

2023-11-10 08:30 UTC, Bidon15 commented on pkg/http/server.go
>  	}
you need to be more precise with handling not expected behaviour here. I.e. we need to retry if we fail, hence it makes sense to put into the else. In addition, do we plan to watch until forever? If no, it's much better to set a clear deadline to this process (can be like 4-5 min) where you pass the context to a watcher function and then exit the for loop gracefully.

Moreover, I highly recommend to go with select here, if you opt for the option I provided above

2023-11-10 08:30 UTC, Bidon15 commented on pkg/http/server.go
> +			go WatchHashMetric(cfg, done)
better use errGo for this and have the WatchHashMetric returning error.

https://medium.com/@yardenlaif/go-sync-or-go-home-errgroup-f91a0ee72d3f

2023-11-13 11:27 UTC, Bidon15 approved these changes
1 nit, apart from that lgtm

2023-11-13 11:27 UTC, Bidon15 commented on pkg/http/server.go
> +				}
[nit]: can be a separate private func to keep it neat 
Can be parked as an issue to move on

2023-11-13 14:25 UTC, merged